login:
    path: /login
    controller: Slashid\Symfony\Controller\LoginController::login

login.callback:
    path: /login/callback
    controller: Slashid\Symfony\Controller\LoginController::loginCallback

webhook:
    path: /slashid/webhook
    controller: Slashid\Symfony\Controller\WebhookController::webhook
