slashid.login:
    path: /login
    controller: SlashId\Symfony\Controller\LoginController::login

slashid.login.callback:
    path: /login/callback
    controller: SlashId\Symfony\Controller\LoginController::loginCallback

slashid.webhook:
    path: /slashid/webhook
    controller: SlashId\Symfony\Controller\WebhookController::webhook
